name: Machine Learning Workflow CI

on:
  push:
    branches: [ main ]

jobs:
  train-model:
    runs-on: ubuntu-latest
    # Menambahkan izin menulis agar robot GitHub bisa mengirim data ke DagsHub/MLflow
    permissions:
      contents: write
      
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.7'

      - name: Install Dependencies
        run: |
          # Instalasi library yang dibutuhkan di environment runner
          pip install mlflow==2.19.0 dagshub scikit-learn pandas matplotlib seaborn

      - name: Run Training Script
        env:
          # Memasukkan Secret DAGSHUB_TOKEN ke dalam environment variable
          # Ini kunci agar robot tidak minta login (AUTHORIZATION REQUIRED) lagi
          DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          # Reviewer mewajibkan perintah 'mlflow run' agar sesuai standar MLOps Dicoding
          # --env-manager local digunakan agar MLflow memakai library yang sudah kita install via pip di atas
          mlflow run MLProject_Folder/ --env-manager local