name: Machine Learning Workflow CI

on:
  push:
    branches: [ main ]

jobs:
  train-model:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.7'

      - name: Install Dependencies
        run: |
          pip install mlflow==2.19.0 dagshub scikit-learn pandas matplotlib seaborn

      - name: Run Training Script
        env:
          # Pastikan Secret DAGSHUB_TOKEN sudah terpasang di GitHub Settings
          DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          # Kita jalankan langsung file python-nya agar lebih stabil
          python MLProject_Folder/modelling.py